### ISSUE TITLE
Implement Email Password Authentication Method

### ISSUE THREAD

**Issue by letsintegreat** [letsintegreat/Tagify#1]
Right now, there is only one method to authenticate - Google. Implement Email Password method of firebase, so users can login with custom email and password.

- [ ] In [Login Screen](https://github.com/letsintegreat/Tagify/blob/main/lib/screens/login_screen.dart), add another button.
- [ ] You have to create two pages for Log in and Sign up separately. As you can see in the [User Model](https://github.com/letsintegreat/Tagify/blob/main/lib/models/user_model.dart), we also need the name of the user, so take name as an input from user in Sign up page.
- [ ] Take the inspiration from Google auth code, and implement the logic of adding the user to the Firestore database, when the user creates a new account.

Ask to be assigned in the comments below before starting to work on this issue. Stick to the contribution guidelines as mentioned in the README file.

**Comment by mauryakshitij** [comment]
I would like to work on this issue, pls assign it to me

**Comment by letsintegreat** [comment]
@mauryakshitij You can start.
