### ISSUE TITLE
Improve Google Sign In 

### ISSUE THREAD

**Issue by mauryakshitij** [letsintegreat/Tagify#22]
The google login option automatically uses the account last used by the user. It does not give the option to choose new account when signing out and logging in again.

Ask to be assigned in the comments below before starting to work on this issue. Stick to the contribution guidelines as mentioned in the README file.

**Comment by letsintegreat** [comment]
@mauryakshitij Interesting, I am marking this issue for Codepeak, however, I don't know how much work would it require. So I will assign the points, after looking at the fix. As per the guidelines, you will get 1 point for good first issue / easy and 3 for intermediate / hard.

**Comment by mauryakshitij** [comment]
I'd like to work on the issue
