### ISSUE TITLE
Use Autocomplete widget in Logic Screen

### ISSUE THREAD

**Issue by letsintegreat** [letsintegreat/Tagify#23]
![image](https://user-images.githubusercontent.com/37345795/206224893-819805eb-5546-4996-9934-0530a7af501c.png)

Right now, while adding a tag to a bucket, user is required to type out the entire name of the tag, and then if the tag exists, it gets added else it doesn't. Your task is to implement [Autocomplete](https://api.flutter.dev/flutter/material/Autocomplete-class.html) widget, and show the list of available tags in auto complete pop up. 

I am not familiar with the widget, so I will give 10 or 20 points depending on the PR.

Ask to be assigned in the comments below before starting to work on this issue. Stick to the contribution guidelines as mentioned in the README file.

**Comment by Tushar98644** [comment]
i would like to contribute...

**Comment by letsintegreat** [comment]
> i would like to contribute...

As I have just assigned you an issue, I would like you to solve that one, before getting yourself assigned to others..

**Comment by Shanta-11** [comment]
assign me pls
