### ISSUE TITLE
Improve UX in Add Group Screen

### ISSUE THREAD

**Issue by chandansgowda** [letsintegreat/Tagify#35]
Currenty, the user is able to add multiple group with the same name since we are not navigating back to the home screen after creating a group. I have attached a screen recording which demonstrates how duplicate groups can be created.

https://user-images.githubusercontent.com/41890434/206958086-70fe2de4-a1ec-4473-992b-d14e0f4177b0.mov

**Comment by chandansgowda** [comment]
Shall I work on this ?

**Comment by letsintegreat** [comment]
@chandansgowda Just assigned you another issue, please work on that first. Currently the issue is up for grabs

**Comment by chandansgowda** [comment]
Hey @letsintegreat ,
I'm done with that one. Shall I take this up ?
