### ISSUE TITLE
Fix the UI for logic_screen.dart

### ISSUE THREAD

**Issue by letsintegreat** [letsintegreat/Tagify#4]
![WhatsApp Image 2022-12-04 at 22 07 30](https://user-images.githubusercontent.com/37345795/205503648-d43113d6-1b0d-434d-b00f-9dd3ed30c4b9.jpg)

As you can see, adding tags in a bucket just squeezes the list of tags into one line, no matter how many tags are there in the bucket. Instead, keep one tag in a line, and wrap the new tag to the next line as we keep adding tags in a bucket.

Ask to be assigned in the comments below before starting to work on this issue. Stick to the contribution guidelines as mentioned in the README file.

**Comment by mauryakshitij** [comment]
pls assign this issue to me
