### ISSUE TITLE
Implement a feature to Resolve a group.

### ISSUE THREAD

**Issue by letsintegreat** [letsintegreat/Tagify#5]
Once a group has served its purpose, the group owner should be able to resolve the group. Right now, we are not saving who is the owner of a group in the group model.

As this issues has been labelled hard, and carries 20 points. You need to figure out what all should be taken care of.

Ask to be assigned in the comments below before starting to work on this issue. Stick to the contribution guidelines as mentioned in the README file.

**Comment by chandansgowda** [comment]
Hey @letsintegreat 
Shall I take this up ?

**Comment by chandansgowda** [comment]
Hey @letsintegreat 
Please review - #20

**Comment by letsintegreat** [comment]
@chandansgowda Hey, from the next when you submit a PR, it would be great if you use this line:

    Closes #5
    
Instead of

    Ref - #5

In this way, when I merge the PR, this issue will automatically be closed!
