### ISSUE TITLE
Reduce the size of the Google icon in Login screen.

### ISSUE THREAD

**Issue by letsintegreat** [letsintegreat/Tagify#7]
**Important: This Issue is only for beginners to Open Source and Flutter. If you have some experience in either of these, go for another issues.**

![WhatsApp Image 2022-12-05 at 00 49 48](https://user-images.githubusercontent.com/37345795/205510884-b098b2ea-1969-42e9-8d5c-0af6c9b9dc89.jpg)

In `login_screen.dart`

Right now the google icon seems to almost the size of the button, reduce the size of it a lil bit.

Ask to be assigned in the comments below before starting to work on this issue. Stick to the contribution guidelines as mentioned in the README file.

**Comment by DevvvvvShah** [comment]
Requesting to be assigned to this issue!

**Comment by letsintegreat** [comment]
@DevvvvvShah All yours!

**Comment by DevvvvvShah** [comment]
https://github.com/letsintegreat/Tagify/pull/25

**Comment by letsintegreat** [comment]
> #25 @letsintegreat

Hey @DevvvvvShah, After creating a PR, you are supposed to mention the issue in its description, not the other way around.

If you write

    Closes #7

in your PR's description, then when that PR is merged, the linked issue will automatically be closed. Please take a note

**Comment by DevvvvvShah** [comment]
> Hey @DevvvvvShah, After creating a PR, you are supposed to mention the issue in its description, not the other way around.
Got it, thanks.
